# main text of home
name: Phoenix Literacy
bio: Self-defining life of Aditya Firman Ihsan 

# twitter summary info
description: A blog about literacy work of Aditya Firman Ihsan

external-image: false
picture: assets/images/profile.jpg

collections: 
- poetry

resume: false
# resume-external: true
# resume-url: https://google.com/?q=my+resume

url:  http://phoenixfin.me

permalink: /:title/

analytics-google: 'UA-113258248-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
# disqus:
#  shortname: mydisqus # enter this from your disqus account
#  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# issuu : aditya-finiarelphoenix
facebook: phoenixfin
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# linkedin: mylinkedin
# youtube: myyoutube
# spotify: myspotify
github: phoenixfin
# quora: userquora
# medium: medium
email: aditya.fphoenix@gmail.com

authors:
    aditya:
        name: Aditya Firman Ihsan
        bio: Just a seeker of truth
        external-image: false
        picture: assets/images/adit.jpg
 #       twitter: =

# options: [normal, large] 
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

creator: Aditya Firman Ihsan

booklet: true
about: true
buku: true
kompilasi: true
arsip: true
monolog: true
puisi: true
opini: true
resensi: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [opini, monolog, resensi]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com
